# Generated by Django 4.2.3 on 2023-08-10 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_bid_listing_alter_comment_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='current_price',
            new_name='highest_bid',
        ),
    ]
